---
title: "sip analisis"
output: html_notebook
---

```{r}
library(phyloseq)
library(microViz)
library(ggdendro)
library(ggpubr)
library(dendextend)
library(patchwork)
library(cowplot)
library(viridis)
require(dplyr)
library(microbiome)
library(vegan)
library(readxl)

```



```{r}

##16 Analisis
rarefied= readRDS("Rarefied16S.RDS")

rarefiedF = subset_samples(rarefied, ID != "H")



```


```{r}


SP16= subset_samples(rarefiedF, Soil== "Pereyra")

# Aggregate the data at the Genus taxonomic rank
SP16=tax_glom(SP16, taxrank= "Genus")

# Filter the taxa based on minimum prevalence and sample abundance
SP16F=SP16%>%
  tax_fix()%>%
  tax_filter(min_prevalence = 0.06, min_sample_abundance = 111)

# Transform the data to compositional
SP16F= transform(SP16F, transform="compositional")

# Melt the phyloseq object to a long-format data frame
mainDF=psmelt(SP16F)


# Initialize a matrix for the data
mainDF$Fraction=as.factor(mainDF$Fraction)
datmat=matrix(nrow= length(unique(mainDF$OTU)), ncol=length(unique(mainDF$ID)))
row.names(datmat)=unique(mainDF$OTU)
colnames(datmat)=unique(mainDF$ID)

# Loop through each unique OTU
for (i in 1:length(unique(mainDF$OTU))){
  #one new data frame for each ASV
  dat1=mainDF[which(mainDF$OTU==unique(mainDF$OTU)[i]),]
  #one new iteration for each microcosm
  for (j in 1:length(unique(mainDF$ID))){
    H=dat1[which(dat1$Fraction=="heavy"&dat1$ID==unique(mainDF$ID)[j]),]$Abundance
    L=dat1[which(dat1$Fraction=="light"&dat1$ID==unique(mainDF$ID)[j]),]$Abundance
    #if(length(L)==0) {L=0.000001}
    #datmat[i,j]=dat1[which(dat1$Fraction=="heavy"&dat1$ID==unique(dat1$ID)[j]),]$Abundance/
    #  dat1[which(dat$Fraction=="light"&dat1$ID==unique(dat1$ID)[j]),]$Abundance
    datmat[i,j]=H/(L+H)
    }
}

datmat.df=as.data.frame(t(datmat))
datmat.df[is.na(datmat.df)] <- 0
datmat.df$Treat=mainDF$Treatment[match(row.names(datmat.df), mainDF$ID)]
datmat.df$Time=mainDF$Time[match(row.names(datmat.df), mainDF$ID)]

# Create a list for comparisons
comparisons=list()
for (i in 1:4){
  Thirteen=datmat.df[which(datmat.df$Treat=="C13"&datmat.df$Time==unique(datmat.df$Time)[i]),]
  Twelve=datmat.df[which(datmat.df$Treat=="C12"&datmat.df$Time==unique(datmat.df$Time)[i]),]
  comparisons=rbind(comparisons,expand.grid(x=row.names(Thirteen), y=row.names(Twelve)))
}

datmat.df=datmat.df[1:(length(datmat.df)-2)]
final=matrix(nrow=nrow(comparisons), ncol=ncol(datmat.df))
colnames(final)=colnames(datmat.df)

#This loop substracts c12 from C13
for (i in 1:nrow(comparisons)){
  final[i,]=t(as.matrix(datmat.df[which(row.names(datmat.df)==comparisons[i,1]),]-datmat.df[which(row.names(datmat.df)==comparisons[i,2]),])[1,])
}

#this comparisons object will become the metadata
comparisons$Time=mainDF$Time[match(comparisons[,1], mainDF$ID)]

#make taxonomy table based on melted object
tax=matrix(nrow = length(unique(mainDF$OTU)), ncol = 0)
row.names(tax)=colnames(final)
tax=as.data.frame(tax)
tax$Phylum=mainDF$Phylum[match(row.names(tax), mainDF$OTU)]
tax$Class=mainDF$Class[match(row.names(tax), mainDF$OTU)]
tax$Order=mainDF$Order[match(row.names(tax), mainDF$OTU)]
tax$Family=mainDF$Family[match(row.names(tax), mainDF$OTU)]
tax$Genus=mainDF$Genus[match(row.names(tax), mainDF$OTU)]
tax=as.matrix(tax)

#merge into a Phyloseq object
output=phyloseq(otu_table(final, taxa_are_rows = FALSE), sample_data(comparisons), tax_table(tax))


otu_mat=output@otu_table@.Data
p.values = matrix(, nrow = ncol(otu_mat))
row.names(p.values) = colnames(otu_mat)


# Apply ANOVA to each column of the OTU matrix
r = apply(otu_mat, 2, function(x) summary(aov(x ~ factor(output@sam_data$Time))))
for (i in 1:ncol(otu_mat)) {
p.values[i, 1] = r[[i]][[1]]$"Pr(>F)"[1]
}
siglevel=0.05
q = p.values[which(rowSums(p.values) < siglevel), ]
a = t(otu_mat)
b = a[row.names(a) %in% row.names(data.frame(q)), ]
(!is.null(tax_table(output, errorIfNULL = FALSE)))
c = (tax_table(output))[row.names((tax_table(output))) %in%
row.names(b), ]
new_physeq = merge_phyloseq(otu_table(b, taxa_are_rows = TRUE),
tax_table(c), sample_data(output))
df = otu_table(new_physeq)
colnames(df) = new_physeq@sam_data$Time


```


```{r}

# Melt the new_physeq object to a long-format data frame
meltout= psmelt(new_physeq)

# Subset the data to include only EF ("Abundance") greater than 0.01
meltF= subset(meltout, meltout$Abundance>0.01)

# Get unique ASVs with EF greater than 0.01
ASVs= unique(meltF$OTU)


# Filter the phyloseq object using ASVs with EF > 0.01
outputF= new_physeq%>%
  tax_select(tax_list = ASVs)

# Create a data frame and calculate the mean EF
meltoF=psmelt(outputF)

df2 <- meltoF %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
              .groups = 'drop') %>%
  as.data.frame()

# Select those ASVs whose mean is greater than 0.015
df2s=subset(df2, df2$Abundance > 0.015)

ASVds= unique(df2s$OTU)

outputFd= new_physeq %>%
  tax_select(tax_list = ASVds)

meltoFd=psmelt(outputFd)


# Create a data frame and calculate the mean EF
df21s <- meltoFd %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
              .groups = 'drop') %>%
  as.data.frame()


# Create a taxonomy table based on the melted object
tax1=matrix(nrow = length(unique(meltoFd$OTU)), ncol = 0)
row.names(tax1)=unique(df21s$OTU)
tax1=as.data.frame(tax1)
tax1$Phylum=meltoFd$Phylum[match(row.names(tax1), meltoFd$OTU)]
tax1$Class=meltoFd$Class[match(row.names(tax1), meltoFd$OTU)]
tax1$Order=meltoFd$Order[match(row.names(tax1), meltoFd$OTU)]
tax1$Family=meltoFd$Family[match(row.names(tax1), meltoFd$OTU)]
tax1$Genus=meltoFd$Genus[match(row.names(tax1), meltoFd$OTU)]

tax1$OTU= row.names(tax1)

# Merge the data frame with the taxonomy table
p3=merge(df21s, tax1, by="OTU")

# Filter the SP16F object using the selected ASVs to obtain the real Abundance of the Enriched Genera in C13-treatment heavy fraction

SP16Fs= SP16F %>%
  tax_select(tax_list = ASVds)

C13= subset_samples(SP16Fs, Treatment=="C13")
C13h= subset_samples(C13, Fraction =="heavy")
C13h= psmelt(C13h)

# Create a data frame and calculate the mean abundance
C13m= C13h %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
            .groups = 'drop') %>%
  as.data.frame()

# Add the mean abundance to the merged data frame
p3$Abundance_tax= C13m$Abundance

#filter by Abundace ("tax_abundance") > 0.05%
p2f= subset(p3, p3$Abundance_tax>0.005)

#Choose those ASV that have EF > 0.015 and Abundance > 5% 
ASVf= unique(p2f$OTU)

#Filter 
outputFd= new_physeq %>%
  tax_select(tax_list = ASVf)
meltoFd=psmelt(outputFd)


df2s <- meltoFd %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
              .groups = 'drop') %>%
  as.data.frame()

tax1=matrix(nrow = length(unique(meltoFd$OTU)), ncol = 0)
row.names(tax1)=unique(df2s$OTU)
tax1=as.data.frame(tax1)
tax1$Phylum=meltoFd$Phylum[match(row.names(tax1), meltoFd$OTU)]
tax1$Class=meltoFd$Class[match(row.names(tax1), meltoFd$OTU)]
tax1$Order=meltoFd$Order[match(row.names(tax1), meltoFd$OTU)]
tax1$Family=meltoFd$Family[match(row.names(tax1), meltoFd$OTU)]
tax1$Genus=meltoFd$Genus[match(row.names(tax1), meltoFd$OTU)]

tax1$OTU= row.names(tax1)

p2f=merge(df2s, tax1, by="OTU")



SP16Fs= SP16F %>%
  tax_select(tax_list = ASVf)


C13= subset_samples(SP16Fs, Treatment=="C13")
C13h= subset_samples(C13, Fraction =="heavy")
C13h= psmelt(C13h)

C13m= C13h %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
            .groups = 'drop') %>%
  as.data.frame()


p2f$Abundance_tax= C13m$Abundance

# Exclude the inoculated Genera
p2m= subset(p2f, Genus != "Burkholderia-Caballeronia-Paraburkholderia")
p2mod= subset(p2m, Genus != "Sphingobium")
p2mod$Time= factor(p2mod$Time)


```

```{r}
ASVf= unique(p2mod$OTU)

dfm= df[ASVf, ]

eudist= vegdist(dfm, method = "euclidean")

dend16 <- as.dendrogram(hclust(eudist, method= "ward.D2"))
ggdendrogram(dend16)

dendro.plot16 <- ggdendrogram(dend16,rotate = T, labels= T) +scale_y_reverse() + theme_dendro()+ theme(plot.margin=unit(c(0.25,-1,0.5,-0.15),"cm"))


write.csv2(p2mod, "Genera-SP-aov0.05-vf.csv")
```



```{r}

# p-value 0.05
p2mod$Genus= factor(p2mod$Genus,
                    levels= c("Lysobacter",
                              "Rhodanobacter",
                              "RB41",
                              "Candidatus_Solibacter",
                              "Subgroup_7",
                              "Methyloligellaceae",
                              "TK10",
                              "Chitinophagaceae",
                              "Bacillus",
                              "Gemmatimonas",
                              "Mycobacterium",
                              "Rokubacteriales",
                              "Candidatus_Udaeobacter",
                              "Acidobacteriales",
                              "Vicinamibacteraceae",
                              "Subgroup_2",
                              "Xanthobacteraceae",
                              "Bradyrhizobium",
                              "Sphingomonas",
                              "Gemmatimonadaceae",
                              "Acidothermus"))

```




```{r}

#Repeat the analysis fo LT-Soil
IPK16= subset_samples(rarefiedF, Soil== "IPK")
IPK16= tax_glom(IPK16, taxrank = "Genus")

IPK16F=IPK16%>%
  tax_fix()%>%
  tax_filter(min_prevalence = 0.06, min_sample_abundance = 111)

IPK16F= transform(IPK16F, transform="compositional")
meltedIPK16F=psmelt(IPK16F)


```

```{r}
mainDF=meltedIPK16F

mainDF$Fraction=as.factor(mainDF$Fraction)
datmat=matrix(nrow= length(unique(mainDF$OTU)), ncol=length(unique(mainDF$ID)))
row.names(datmat)=unique(mainDF$OTU)
colnames(datmat)=unique(mainDF$ID)


for (i in 1:length(unique(mainDF$OTU))){
  #one new data frame for each ASV
  dat1=mainDF[which(mainDF$OTU==unique(mainDF$OTU)[i]),]
  #one new iteration for each microcosm
  for (j in 1:length(unique(mainDF$ID))){
    H=dat1[which(dat1$Fraction=="heavy"&dat1$ID==unique(mainDF$ID)[j]),]$Abundance
    L=dat1[which(dat1$Fraction=="light"&dat1$ID==unique(mainDF$ID)[j]),]$Abundance
    #if(length(L)==0) {L=0.000001}
    #datmat[i,j]=dat1[which(dat1$Fraction=="heavy"&dat1$ID==unique(dat1$ID)[j]),]$Abundance/
    #  dat1[which(dat$Fraction=="light"&dat1$ID==unique(dat1$ID)[j]),]$Abundance
    datmat[i,j]=H/(L+H)
    }
}

datmat.df=as.data.frame(t(datmat))
datmat.df[is.na(datmat.df)] <- 0
datmat.df$Treat=mainDF$Treatment[match(row.names(datmat.df), mainDF$ID)]
datmat.df$Time=mainDF$Time[match(row.names(datmat.df), mainDF$ID)]

comparisons=list()
for (i in 1:4){
  Thirteen=datmat.df[which(datmat.df$Treat=="C13"&datmat.df$Time==unique(datmat.df$Time)[i]),]
  Twelve=datmat.df[which(datmat.df$Treat=="C12"&datmat.df$Time==unique(datmat.df$Time)[i]),]
  comparisons=rbind(comparisons,expand.grid(x=row.names(Thirteen), y=row.names(Twelve)))
}

datmat.df=datmat.df[1:(length(datmat.df)-2)]
final=matrix(nrow=nrow(comparisons), ncol=ncol(datmat.df))
colnames(final)=colnames(datmat.df)

#This loop substracts c12 from C13
for (i in 1:nrow(comparisons)){
  final[i,]=t(as.matrix(datmat.df[which(row.names(datmat.df)==comparisons[i,1]),]-datmat.df[which(row.names(datmat.df)==comparisons[i,2]),])[1,])
}

#this comparisons object will become the metadata
comparisons$Time=mainDF$Time[match(comparisons[,1], mainDF$ID)]

#make taxonomy table based on melted object
tax=matrix(nrow = length(unique(mainDF$OTU)), ncol = 0)
row.names(tax)=colnames(final)
tax=as.data.frame(tax)
tax$Phylum=mainDF$Phylum[match(row.names(tax), mainDF$OTU)]
tax$Class=mainDF$Class[match(row.names(tax), mainDF$OTU)]
tax$Order=mainDF$Order[match(row.names(tax), mainDF$OTU)]
tax$Family=mainDF$Family[match(row.names(tax), mainDF$OTU)]
tax$Genus=mainDF$Genus[match(row.names(tax), mainDF$OTU)]
tax=as.matrix(tax)

#merge into a Phyloseq object
output=phyloseq(otu_table(final, taxa_are_rows = FALSE), sample_data(comparisons), tax_table(tax))


require(ComplexHeatmap)
otu_mat=output@otu_table@.Data
p.values = matrix(, nrow = ncol(otu_mat))
row.names(p.values) = colnames(otu_mat)



r = apply(otu_mat, 2, function(x) summary(aov(x ~ factor(output@sam_data$Time))))
for (i in 1:ncol(otu_mat)) {
p.values[i, 1] = r[[i]][[1]]$"Pr(>F)"[1]
}
siglevel=0.05
q = p.values[which(rowSums(p.values) < siglevel), ]
a = t(otu_mat)
b = a[row.names(a) %in% row.names(data.frame(q)), ]
(!is.null(tax_table(output, errorIfNULL = FALSE)))
c = (tax_table(output))[row.names((tax_table(output))) %in%
row.names(b), ]
new_physeq = merge_phyloseq(otu_table(b, taxa_are_rows = TRUE),
tax_table(c), sample_data(output))
df = otu_table(new_physeq)
colnames(df) = new_physeq@sam_data$Time



```

```{r}

meltout= psmelt(new_physeq)
meltF= subset(meltout, meltout$Abundance>0.01)

ASVs= unique(meltF$OTU)


outputF= output %>%
  tax_select(tax_list = ASVs)

meltoF=psmelt(outputF)
df2 <- meltoF %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
              .groups = 'drop') %>%
  as.data.frame()


df2s=subset(df2, df2$Abundance > 0.015)
ASVds= unique(df2s$OTU)

outputFd= output %>%
  tax_select(tax_list = ASVds)
meltoFd=psmelt(outputFd)


df2s <- meltoFd %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
              .groups = 'drop') %>%
  as.data.frame()

tax1=matrix(nrow = length(unique(meltoFd$OTU)), ncol = 0)
row.names(tax1)=unique(df2s$OTU)
tax1=as.data.frame(tax1)
tax1$Phylum=meltoFd$Phylum[match(row.names(tax1), meltoFd$OTU)]
tax1$Class=meltoFd$Class[match(row.names(tax1), meltoFd$OTU)]
tax1$Order=meltoFd$Order[match(row.names(tax1), meltoFd$OTU)]
tax1$Family=meltoFd$Family[match(row.names(tax1), meltoFd$OTU)]
tax1$Genus=meltoFd$Genus[match(row.names(tax1), meltoFd$OTU)]

tax1$OTU= row.names(tax1)


p2=merge(df2s, tax1, by="OTU")



IPK16Fs= IPK16F %>%
  tax_select(tax_list = ASVds)


C13= subset_samples(IPK16Fs, Treatment=="C13")
C13h= subset_samples(C13, Fraction =="heavy")
C13h= psmelt(C13h)

C13m= C13h %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
            .groups = 'drop') %>%
  as.data.frame()


p2$Abundance_tax= C13m$Abundance

p2$Time= as.factor(p2$Time)


p2f= subset(p2, p2$Abundance_tax>0.005)
ASVf= unique(p2f$OTU)

outputFd= output %>%
  tax_select(tax_list = ASVf)
meltoFd=psmelt(outputFd)


df2s <- meltoFd %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
              .groups = 'drop') %>%
  as.data.frame()

tax1=matrix(nrow = length(unique(meltoFd$OTU)), ncol = 0)
row.names(tax1)=unique(df2s$OTU)
tax1=as.data.frame(tax1)
tax1$Phylum=meltoFd$Phylum[match(row.names(tax1), meltoFd$OTU)]
tax1$Class=meltoFd$Class[match(row.names(tax1), meltoFd$OTU)]
tax1$Order=meltoFd$Order[match(row.names(tax1), meltoFd$OTU)]
tax1$Family=meltoFd$Family[match(row.names(tax1), meltoFd$OTU)]
tax1$Genus=meltoFd$Genus[match(row.names(tax1), meltoFd$OTU)]

tax1$OTU= row.names(tax1)

p2=merge(df2s, tax1, by="OTU")


IPK16Fs= IPK16F %>%
  tax_select(tax_list = ASVf)


C13= subset_samples(IPK16Fs, Treatment=="C13")
C13h= subset_samples(C13, Fraction =="heavy")
C13h= psmelt(C13h)

C13m= C13h %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
            .groups = 'drop') %>%
  as.data.frame()


p2$Abundance_tax= C13m$Abundance
p2$Time= factor(p2$Time)



```


```{r}
ASVf= unique(p2$OTU)

dfm= df[ASVf, ]

eudistIPK= vegdist(dfm, method = "euclidean")

dend16IPK <- as.dendrogram(hclust(eudistIPK, method= "ward.D2"))

dendroIPK16 <- ggdendrogram(dend16IPK,rotate = T, labels= T) +scale_y_reverse() + theme_dendro()+ 
  theme(plot.margin=unit(c(0.25,-1,0.5,-0.15),"cm"))
```



```{r}

p2$Genus=  factor(p2$Genus,
                  levels= c("Promicromonospora",
                            "WN-HWB-116",
                            "67-14"))

View(p2)

write.csv2(p2,"Genera16S-IPK-aov0.05-vf-ambk.csv")


```

```{r}

#FIGURE 3
p3= read.csv2("Genera-SP-aov0.05-vf.csv")


p3$Time= factor(p3$Time)

p3$Genus= factor(p3$Genus,
                    levels= c("Lysobacter",
                              "Rhodanobacter",
                              "RB41",
                              "Candidatus_Solibacter",
                              "Subgroup_7",
                              "Methyloligellaceae",
                              "TK10",
                              "Chitinophagaceae",
                              "Bacillus",
                              "Gemmatimonas",
                              "Mycobacterium",
                              "Rokubacteriales",
                              "Candidatus_Udaeobacter",
                              "Acidobacteriales",
                              "Vicinamibacteraceae",
                              "Subgroup_2",
                              "Xanthobacteraceae",
                              "Bradyrhizobium",
                              "Sphingomonas",
                              "Gemmatimonadaceae",
                              "Acidothermus"))

p3$Abundance_tax1 = p3$Abundance_tax*100

g3=ggballoonplot(p3,x="Time", y="Genus", fill= "Abundance",  size="Abundance_tax1", color= "black") + 
  labs(fill= "EF", size="Relative Abundance" )+
  scale_fill_viridis(option= "viridis",direction = 1, limits= c(0.015,0.35), na.value= "white")+
  guides(fill=guide_colorbar(order =1 ))+ scale_size_continuous(limits = c(0, 50), range = c(0, 15))+
  theme_bw()

g3=g3+ guides(y.sec=guide_axis())+ theme(axis.text.y.left = element_blank()) + theme(plot.margin=unit(c(0.01,6.5,0.01,0.5),"cm"))

g3= g3 + theme(axis.text.y.right = element_text(size=14,  color = "black"),
                  axis.text.x = element_text(size=13),
                  legend.text = element_text(size=12),
                  legend.title = element_text(size=13))+
  theme(legend.spacing.y = unit(0.045, "cm"))+ ggtitle("  ST Soil")





g3=g3 + theme(axis.text.y.right = element_text(size=15, color= "black"),
              axis.text.x = element_text(size=14))+  annotate(
                xmin = 4.43, xmax = 4.55,
                ymin = c(0.5,1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5,11.5,12.5,13.5,14.5,15.5,16.5,17.5,18.5,19.5,20.5),
                ymax = c(1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5,11.5,12.5,13.5,14.5,15.5,16.5,17.5,18.5,19.5,20.5,Inf),
                geom = "rect",
                fill = c("#3288C0",
                         "#3288C0",
                         "#9E1B47",
                         "#9E1B47",
                         "#9E1B47",
                         "#3288C0",
                         "#FBDE89",
                         "#F6AC62",
                         "#E3E898",
                         "#AAD2A1",
                         "#D73E50",
                         "#68C0A5",
                         "#5D529F",
                         "#9E1B47",
                         "#9E1B47",
                         "#9E1B47",
                         "#3288C0",
                         "#3288C0",
                         "#3288C0",
                         "#AAD2A1",
                         "#D73E50"
                         ))

p4= read.csv2("Genera16S-IPK-aov0.05-vf-ambk.csv")

View(p4)
p4$Time= factor(p4$Time,
                levels= c("0", "7", "15"))

p4$Genus=  factor(p4$Genus,
                  levels= c("Promicromonospora",
                            "WN-HWB-116",
                            "67-14"))
p4$Abundance_tax1 = p4$Abundance_tax*100




g5=ggballoonplot(p4,x="Time", y="Genus", fill= "Abundance",  size="Abundance_tax1", color= "black") + 
  labs(fill= "EF", size="Relative Abundance" )+
  scale_fill_viridis(option= "viridis",direction = 1, limits= c(0.015,0.35), na.value= "white")+
  guides(fill=guide_colorbar(order =1 ))+ scale_size_continuous(limits = c(0, 50), range = c(0, 15))+
  theme_bw()

g5=g5 + guides(y.sec=guide_axis())+ theme(axis.text.y.left = element_blank()) +theme(plot.margin=unit(c(0.75,6.5,1,0.5),"cm"))

g5=g5 + theme(axis.text.y.right = element_text(size=14,  color = "black"),
              axis.text.x = element_text(size=13),
              legend.text = element_text(size=12),
              legend.title = element_text(size=13))+
  theme(legend.spacing.y = unit(0.045, "cm"))+ ggtitle("  LT Soil")

g5= g5+ annotate(
  xmin = 3.425, xmax = 3.55,
  ymin = c(0.5,1.5,2.5),
  ymax = c(1.5,2.5,Inf),
  geom = "rect",
  fill = c("#3288C0",
           "#D73E50",
           "#D73E50"
           ))


## legend for annotation

bacteria <- read_excel("C:/Users/esteb/Desktop/Investigacion/paper sip/re analisis Sip/graficas nuevas/Graficas Figura 3/colores bacterias.xlsx")

paleta13= c(  "#9E1B47","#D73E50", "#F6AC62", "#FBDE89","#E3E898",
              "#AAD2A1", "#68C0A5", "#3288C0", "#5D529F")

bacteria$Phylum = factor(bacteria$Phylum,
                         levels = c("Acidobacteriota", "Actinomycetota", "Bacteroidota", "Chloroflexota", "Bacillota", "Gemmatimonadota",
                                    "Methylomirabilota", "Pseudomonadota", "Verrucomicrobiota"))

p1=ggplot(bacteria, aes(Phylum, valor, fill= Phylum)) + geom_bar(stat= "identity") + scale_fill_manual(values=paleta13)+
  labs(fill= "Phylum") + theme(legend.text = element_text(size=15),
                               legend.title = element_text(size=16))

label1= ggpubr::get_legend(p1)

lab1=as_ggplot(label1)

g3=g3+ theme(legend.text = element_text(size=15),
             legend.title = element_text(size=16))

label2= ggpubr::get_legend(g3)
lab2=as_ggplot(label2)





G3=g3/g5 + plot_layout(heights = c(6,1))+ plot_annotation(tag_levels = "A") & theme(legend.position = "none")&
  theme(plot.tag = element_text(size = 15),
        title = element_text(size=16),)

G4=G3 + inset_element(lab1, 1.7575,13.5,0.95,1.05) + inset_element(lab2, 1.7525,4.45,0.95,1.05)& ylab(NULL)


ggsave("Figure 3.pdf", G4, height = 8.5, width = 15.75)
```















```{r}
#Repeat the Analysis for 18S

rarefied18S= readRDS("rarefied18Sn.RDS")


colnames(rarefied18S@otu_table)= paste0 ("ASV", 1: ncol(rarefied18S@otu_table))
row.names(rarefied18S@tax_table)= colnames(rarefied18S@otu_table)


tax2 = data.frame(rarefied18S@tax_table)
sample.data = data.frame(rarefied18S@sam_data)

#Correction of the names of the following genera

tax2$Genus[tax2$Genus == "Filamoeba_sp._I4_5E"] <- "Filamoeba"
tax2$Genus[tax2$Genus == "Filamoeba_nolandi"] <- "Filamoeba"
tax2$Family[tax2$Family == "Filamoeba_sp._I4_5E"] <- "Filamoeba"
tax2$Family[tax2$Family == "Filamoeba_nolandi"] <- "Filamoeba"


rarefied18S <- phyloseq(otu_table(rarefied18S), tax_table(as.matrix(tax2)), sample_data(sample.data))

tax_table(rarefied18S) <- tax_table(rarefied18S)[,1:7]

rarefied18SF = subset_samples(rarefied18S, ID != "H")

#ST SOIL
SP18= subset_samples(rarefied18SF, Soil== "Pereyra")

tax_table(SP18) <- tax_table(SP18)[,1:7]


SP18F=SP18%>%
  tax_fix()%>%
  tax_filter(min_prevalence = 0.06, min_sample_abundance = 238)

SP18F= transform(SP18F, transform="compositional")


```





```{r}

SP18= subset_samples(rarefied18SF, Soil== "Pereyra")

tax_table(SP18) <- tax_table(SP18)[,1:7]

SP18= tax_glom(SP18, taxrank = "Genus")

SP18F=SP18%>%
  tax_fix()%>%
  tax_filter(min_prevalence = 0.06, min_sample_abundance = 238)

SP18F= transform(SP18F, transform="compositional")


meltedSP18F=psmelt(SP18F)
```

```{r}
mainDF=meltedSP18F

mainDF$Fraction=as.factor(mainDF$Fraction)
datmat=matrix(nrow= length(unique(mainDF$OTU)), ncol=length(unique(mainDF$ID)))
row.names(datmat)=unique(mainDF$OTU)
colnames(datmat)=unique(mainDF$ID)


for (i in 1:length(unique(mainDF$OTU))){
  #one new data frame for each ASV
  dat1=mainDF[which(mainDF$OTU==unique(mainDF$OTU)[i]),]
  #one new iteration for each microcosm
  for (j in 1:length(unique(mainDF$ID))){
    H=dat1[which(dat1$Fraction=="heavy"&dat1$ID==unique(mainDF$ID)[j]),]$Abundance
    L=dat1[which(dat1$Fraction=="light"&dat1$ID==unique(mainDF$ID)[j]),]$Abundance
    #if(length(L)==0) {L=0.000001}
    #datmat[i,j]=dat1[which(dat1$Fraction=="heavy"&dat1$ID==unique(dat1$ID)[j]),]$Abundance/
    #  dat1[which(dat$Fraction=="light"&dat1$ID==unique(dat1$ID)[j]),]$Abundance
    datmat[i,j]=H/(L+H)
    }
}

datmat.df=as.data.frame(t(datmat))
datmat.df[is.na(datmat.df)] <- 0
datmat.df$Treat=mainDF$Treatment[match(row.names(datmat.df), mainDF$ID)]
datmat.df$Time=mainDF$Time[match(row.names(datmat.df), mainDF$ID)]

comparisons=list()
for (i in 1:4){
  Thirteen=datmat.df[which(datmat.df$Treat=="C13"&datmat.df$Time==unique(datmat.df$Time)[i]),]
  Twelve=datmat.df[which(datmat.df$Treat=="C12"&datmat.df$Time==unique(datmat.df$Time)[i]),]
  comparisons=rbind(comparisons,expand.grid(x=row.names(Thirteen), y=row.names(Twelve)))
}

datmat.df=datmat.df[1:(length(datmat.df)-2)]
final=matrix(nrow=nrow(comparisons), ncol=ncol(datmat.df))
colnames(final)=colnames(datmat.df)

#This loop substracts c12 from C13
for (i in 1:nrow(comparisons)){
  final[i,]=t(as.matrix(datmat.df[which(row.names(datmat.df)==comparisons[i,1]),]-datmat.df[which(row.names(datmat.df)==comparisons[i,2]),])[1,])
}

#this comparisons object will become the metadata
comparisons$Time=mainDF$Time[match(comparisons[,1], mainDF$ID)]

#make taxonomy table based on melted object
tax=matrix(nrow = length(unique(mainDF$OTU)), ncol = 0)
row.names(tax)=colnames(final)
tax=as.data.frame(tax)
tax$Phylum=mainDF$Phylum[match(row.names(tax), mainDF$OTU)]
tax$Class=mainDF$Class[match(row.names(tax), mainDF$OTU)]
tax$Order=mainDF$Order[match(row.names(tax), mainDF$OTU)]
tax$Family=mainDF$Family[match(row.names(tax), mainDF$OTU)]
tax$Genus=mainDF$Genus[match(row.names(tax), mainDF$OTU)]
tax=as.matrix(tax)

#merge into a Phyloseq object
output=phyloseq(otu_table(final, taxa_are_rows = FALSE), sample_data(comparisons), tax_table(tax))


require(ComplexHeatmap)
otu_mat=output@otu_table@.Data
p.values = matrix(, nrow = ncol(otu_mat))
row.names(p.values) = colnames(otu_mat)


r = apply(otu_mat, 2, function(x) summary(aov(x ~ factor(output@sam_data$Time))))
for (i in 1:ncol(otu_mat)) {
p.values[i, 1] = r[[i]][[1]]$"Pr(>F)"[1]
}
siglevel=0.05
q = p.values[which(rowSums(p.values) < siglevel), ]
a = t(otu_mat)
b = a[row.names(a) %in% row.names(data.frame(q)), ]
(!is.null(tax_table(output, errorIfNULL = FALSE)))
c = (tax_table(output))[row.names((tax_table(output))) %in%
row.names(b), ]
new_physeq = merge_phyloseq(otu_table(b, taxa_are_rows = TRUE),
tax_table(c), sample_data(output))
df = otu_table(new_physeq)
colnames(df) = new_physeq@sam_data$Time




```


```{r}
meltout= psmelt(new_physeq)
meltF= subset(meltout, meltout$Abundance>0.01)

ASVs= unique(meltF$OTU)


outputF= new_physeq %>%
  tax_select(tax_list = ASVs)

meltoF=psmelt(outputF)

df2 <- meltoF %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
              .groups = 'drop') %>%
  as.data.frame()


df2s=subset(df2, df2$Abundance > 0.015)

ASVds= unique(df2s$OTU)

outputFd= output %>%
  tax_select(tax_list = ASVds)
meltoFd=psmelt(outputFd)


df2s <- meltoFd %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
              .groups = 'drop') %>%
  as.data.frame()

tax1=matrix(nrow = length(unique(meltoFd$OTU)), ncol = 0)
row.names(tax1)=unique(df2s$OTU)
tax1=as.data.frame(tax1)
tax1$Phylum=meltoFd$Phylum[match(row.names(tax1), meltoFd$OTU)]
tax1$Class=meltoFd$Class[match(row.names(tax1), meltoFd$OTU)]
tax1$Order=meltoFd$Order[match(row.names(tax1), meltoFd$OTU)]
tax1$Family=meltoFd$Family[match(row.names(tax1), meltoFd$OTU)]
tax1$Genus=meltoFd$Genus[match(row.names(tax1), meltoFd$OTU)]

tax1$OTU= row.names(tax1)

p2=merge(df2s, tax1, by="OTU")


SP18SFs= SP18F %>%
  tax_select(tax_list = ASVds)


C13= subset_samples(SP18SFs, Treatment=="C13")
C13h= subset_samples(C13, Fraction =="heavy")
C13h= psmelt(C13h)
C13m= C13h %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
            .groups = 'drop') %>%
  as.data.frame()


p2$Abundance_tax= C13m$Abundance


p2$Time= as.factor(p2$Time)


p2f= subset(p2, p2$Abundance_tax>0.005)
ASVf= unique(p2f$OTU)

outputFd= new_physeq %>%
  tax_select(tax_list = ASVf)
meltoFd=psmelt(outputFd)


df2s <- meltoFd %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
              .groups = 'drop') %>%
  as.data.frame()

tax1=matrix(nrow = length(unique(meltoFd$OTU)), ncol = 0)
row.names(tax1)=unique(df2s$OTU)
tax1=as.data.frame(tax1)
tax1$Phylum=meltoFd$Phylum[match(row.names(tax1), meltoFd$OTU)]
tax1$Class=meltoFd$Class[match(row.names(tax1), meltoFd$OTU)]
tax1$Order=meltoFd$Order[match(row.names(tax1), meltoFd$OTU)]
tax1$Family=meltoFd$Family[match(row.names(tax1), meltoFd$OTU)]
tax1$Genus=meltoFd$Genus[match(row.names(tax1), meltoFd$OTU)]

tax1$OTU= row.names(tax1)

p2=merge(df2s, tax1, by="OTU")


SP18Fs= SP18F %>%
  tax_select(tax_list = ASVf)


C13= subset_samples(SP18Fs, Treatment=="C13")
C13h= subset_samples(C13, Fraction =="heavy")
C13h= psmelt(C13h)

C13m= C13h %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
            .groups = 'drop') %>%
  as.data.frame()


p2$Abundance_tax= C13m$Abundance
p2$Time= factor(p2$Time)


```

```{r}

ASVf= unique(p2$OTU)

dfm= df[ASVf, ]


eudist18= vegdist(dfm, method = "euclidean")

dend18 <- as.dendrogram(hclust(eudist18, method= "ward.D2"))

dendro18 <- ggdendrogram(dend18,rotate = T, labels= T) +scale_y_reverse() + theme_dendro()+ 
  theme(plot.margin=unit(c(0.25,-1,0.5,-0.15),"cm"))

```

```{r}
p2[17:20, "Genus"] = "Sorodiplophrys"
p2[29:32, "Genus"] = "uncultured Cercomonadidae"
p2[41:44, "Genus"] = "uncultured Thecofilosea"
p2[53:56, "Genus"] = "uncultured Agaricales"


#p-value 0.05
p2$Genus = factor(p2$Genus,
                  levels = c("uncultured Agaricales",
                             "LKM11",
                             "Filamoeba",
                             "uncultured_eukaryote",
                             "Cercomonas",
                             "Mortierella",
                             "D3P05A02",
                             "Sorosphaerula",
                             "Acanthamoeba",
                             "Allas",
                             "Sorodiplophrys",
                             "Telaepolella_tubasferens",
                             "uncultured Thecofilosea",
                             "Hygrocybe",
                             "uncultured Cercomonadidae"),
                  labels= c("uncultured Agaricales",
                            "LKM11",
                            "Filamoeba",
                            "uncultured_eukaryote",
                            "Cercomonas",
                            "Mortierella",
                            "D3P05A02",
                            "Sorosphaerula",
                            "Acanthamoeba",
                            "Allas",
                            "Sorodiplophrys",
                            "Telaepolella",
                            "uncultured Thecofilosea",
                            "Hygrocybe",
                            "uncultured Cercomonadidae"))



View(p2)

write.csv2(p2, "Genus18S-SP-aov0.05-vf.csv")

```







```{r}

#LT soil 18S
IPK18= subset_samples(rarefied18SF, Soil== "IPK")

tax_table(IPK18) <- tax_table(IPK18)[,1:7]
IPK18= tax_glom(IPK18, taxrank = "Genus")

IPK18F=IPK18%>%
  tax_fix()%>%
  tax_filter(min_prevalence = 0.06, min_sample_abundance = 238)

IPK18F= transform(IPK18F, transform="compositional")


meltedIPK18F=psmelt(IPK18F)

```

```{r}
mainDF=meltedIPK18F

mainDF$Fraction=as.factor(mainDF$Fraction)
datmat=matrix(nrow= length(unique(mainDF$OTU)), ncol=length(unique(mainDF$ID)))
row.names(datmat)=unique(mainDF$OTU)
colnames(datmat)=unique(mainDF$ID)


for (i in 1:length(unique(mainDF$OTU))){
  #one new data frame for each ASV
  dat1=mainDF[which(mainDF$OTU==unique(mainDF$OTU)[i]),]
  #one new iteration for each microcosm
  for (j in 1:length(unique(mainDF$ID))){
    H=dat1[which(dat1$Fraction=="heavy"&dat1$ID==unique(mainDF$ID)[j]),]$Abundance
    L=dat1[which(dat1$Fraction=="light"&dat1$ID==unique(mainDF$ID)[j]),]$Abundance
    #if(length(L)==0) {L=0.000001}
    #datmat[i,j]=dat1[which(dat1$Fraction=="heavy"&dat1$ID==unique(dat1$ID)[j]),]$Abundance/
    #  dat1[which(dat$Fraction=="light"&dat1$ID==unique(dat1$ID)[j]),]$Abundance
    datmat[i,j]=H/(L+H)
    }
}

datmat.df=as.data.frame(t(datmat))
datmat.df[is.na(datmat.df)] <- 0
datmat.df$Treat=mainDF$Treatment[match(row.names(datmat.df), mainDF$ID)]
datmat.df$Time=mainDF$Time[match(row.names(datmat.df), mainDF$ID)]

comparisons=list()
for (i in 1:4){
  Thirteen=datmat.df[which(datmat.df$Treat=="C13"&datmat.df$Time==unique(datmat.df$Time)[i]),]
  Twelve=datmat.df[which(datmat.df$Treat=="C12"&datmat.df$Time==unique(datmat.df$Time)[i]),]
  comparisons=rbind(comparisons,expand.grid(x=row.names(Thirteen), y=row.names(Twelve)))
}

datmat.df=datmat.df[1:(length(datmat.df)-2)]
final=matrix(nrow=nrow(comparisons), ncol=ncol(datmat.df))
colnames(final)=colnames(datmat.df)

#This loop substracts c12 from C13
for (i in 1:nrow(comparisons)){
  final[i,]=t(as.matrix(datmat.df[which(row.names(datmat.df)==comparisons[i,1]),]-datmat.df[which(row.names(datmat.df)==comparisons[i,2]),])[1,])
}

#this comparisons object will become the metadata
comparisons$Time=mainDF$Time[match(comparisons[,1], mainDF$ID)]

#make taxonomy table based on melted object
tax=matrix(nrow = length(unique(mainDF$OTU)), ncol = 0)
row.names(tax)=colnames(final)
tax=as.data.frame(tax)
tax$Phylum=mainDF$Phylum[match(row.names(tax), mainDF$OTU)]
tax$Class=mainDF$Class[match(row.names(tax), mainDF$OTU)]
tax$Order=mainDF$Order[match(row.names(tax), mainDF$OTU)]
tax$Family=mainDF$Family[match(row.names(tax), mainDF$OTU)]
tax$Genus=mainDF$Genus[match(row.names(tax), mainDF$OTU)]
tax=as.matrix(tax)

#merge into a Phyloseq object
output=phyloseq(otu_table(final, taxa_are_rows = FALSE), sample_data(comparisons), tax_table(tax))


require(ComplexHeatmap)
otu_mat=output@otu_table@.Data
p.values = matrix(, nrow = ncol(otu_mat))
row.names(p.values) = colnames(otu_mat)


r = apply(otu_mat, 2, function(x) summary(aov(x ~ factor(output@sam_data$Time))))
for (i in 1:ncol(otu_mat)) {
p.values[i, 1] = r[[i]][[1]]$"Pr(>F)"[1]
}
siglevel=0.05
q = p.values[which(rowSums(p.values) < siglevel), ]
a = t(otu_mat)
b = a[row.names(a) %in% row.names(data.frame(q)), ]
(!is.null(tax_table(output, errorIfNULL = FALSE)))
c = (tax_table(output))[row.names((tax_table(output))) %in%
row.names(b), ]
new_physeq = merge_phyloseq(otu_table(b, taxa_are_rows = TRUE),
tax_table(c), sample_data(output))
df = otu_table(new_physeq)
colnames(df) = new_physeq@sam_data$Time

```

```{r}
meltout= psmelt(new_physeq)
meltF= subset(meltout, meltout$Abundance>0.01)

ASVs= unique(meltF$OTU)


outputF= new_physeq %>%
  tax_select(tax_list = ASVs)

meltoF=psmelt(outputF)

df2 <- meltoF %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
              .groups = 'drop') %>%
  as.data.frame()

# filtro aquellos ASVs cuya media de EF es mayor a 0.015
df2s=subset(df2, df2$Abundance > 0.015)

ASVds= unique(df2s$OTU)

outputFd= output %>%
  tax_select(tax_list = ASVds)
meltoFd=psmelt(outputFd)


df2s <- meltoFd %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
              .groups = 'drop') %>%
  as.data.frame()

tax1=matrix(nrow = length(unique(meltoFd$OTU)), ncol = 0)
row.names(tax1)=unique(df2s$OTU)
tax1=as.data.frame(tax1)
tax1$Phylum=meltoFd$Phylum[match(row.names(tax1), meltoFd$OTU)]
tax1$Class=meltoFd$Class[match(row.names(tax1), meltoFd$OTU)]
tax1$Order=meltoFd$Order[match(row.names(tax1), meltoFd$OTU)]
tax1$Family=meltoFd$Family[match(row.names(tax1), meltoFd$OTU)]
tax1$Genus=meltoFd$Genus[match(row.names(tax1), meltoFd$OTU)]

tax1$OTU= row.names(tax1)

p2=merge(df2s, tax1, by="OTU")


IPK18SFs= IPK18F %>%
  tax_select(tax_list = ASVds)


C13= subset_samples(IPK18SFs, Treatment=="C13")
C13h= subset_samples(C13, Fraction =="heavy")
C13h= psmelt(C13h)
C13m= C13h %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
            .groups = 'drop') %>%
  as.data.frame()


p2$Abundance_tax= C13m$Abundance


p2$Time= as.factor(p2$Time)


p2f= subset(p2, p2$Abundance_tax>0.005)
ASVf= unique(p2f$OTU)

outputFd= new_physeq %>%
  tax_select(tax_list = ASVf)
meltoFd=psmelt(outputFd)


df2s <- meltoFd %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
              .groups = 'drop') %>%
  as.data.frame()

tax1=matrix(nrow = length(unique(meltoFd$OTU)), ncol = 0)
row.names(tax1)=unique(df2s$OTU)
tax1=as.data.frame(tax1)
tax1$Phylum=meltoFd$Phylum[match(row.names(tax1), meltoFd$OTU)]
tax1$Class=meltoFd$Class[match(row.names(tax1), meltoFd$OTU)]
tax1$Order=meltoFd$Order[match(row.names(tax1), meltoFd$OTU)]
tax1$Family=meltoFd$Family[match(row.names(tax1), meltoFd$OTU)]
tax1$Genus=meltoFd$Genus[match(row.names(tax1), meltoFd$OTU)]

tax1$OTU= row.names(tax1)

p2=merge(df2s, tax1, by="OTU")


IPK18Fs= IPK18F %>%
  tax_select(tax_list = ASVf)


C13= subset_samples(IPK18Fs, Treatment=="C13")
C13h= subset_samples(C13, Fraction =="heavy")
C13h= psmelt(C13h)

C13m= C13h %>% group_by(OTU,Time) %>% 
  summarise(Abundance=mean(Abundance),
            .groups = 'drop') %>%
  as.data.frame()


p2$Abundance_tax= C13m$Abundance
p2$Time= factor(p2$Time)


```

```{r}
ASVf= unique(p2$OTU)

dfm= df[ASVf, ]


eudistIPK18= vegdist(dfm, method = "euclidean")

dendIPK18 <- as.dendrogram(hclust(eudistIPK18, method= "ward.D2"))

dendroIPK18 <- ggdendrogram(dendIPK18,rotate = T, labels= T) +scale_y_reverse() + theme_dendro()+ 
  theme(plot.margin=unit(c(0.25,-1,0.5,-0.15),"cm"))


```

```{r}
p2$Genus= factor(p2$Genus,
                 levels= c("Opisthonecta",
                           "Spumella",
                           "D3P05A02",
                           "Filamoeba",
                           "Lobochlamys",
                           "Chlamydomyxa",
                           "Colpoda"))
write.csv2(p2, "Genus18S-IPK-aov0.05-vf.csv")

```

```{r}

#Figure 4
p3= read.csv2("Genus18S-SP-aov0.05-vf.csv")


p3$Time= factor(p3$Time,
                levels=c("0", "7", "15", "30"))
p3$Genus = factor(p3$Genus,
                      levels= c("uncultured Agaricales",
                            "LKM11",
                            "Filamoeba",
                            "uncultured_eukaryote",
                            "Cercomonas",
                            "Mortierella",
                            "D3P05A02",
                            "Sorosphaerula",
                            "Acanthamoeba",
                            "Allas",
                            "Sorodiplophrys",
                            "Telaepolella",
                            "uncultured Thecofilosea",
                            "Hygrocybe",
                            "uncultured Cercomonadidae"))

p3$Abundance_tax1 = p3$Abundance_tax*100

g4=ggballoonplot(p3,x="Time", y="Genus", fill= "Abundance",  size="Abundance_tax1", color= "black") + 
  labs(fill= "EF", size="Relative Abundance" )+
  scale_fill_viridis(option= "viridis",direction = 1, limits= c(0.015,0.35), na.value= "white")+
  guides(fill=guide_colorbar(order =1))+ scale_size_continuous(limits = c(0, 50), range = c(0, 16))+ 
  theme_bw()

g4=g4 + guides(y.sec=guide_axis())+ theme(axis.text.y.left = element_blank())+ 
  theme(plot.margin=unit(c(0.15,6,0.15,0.5),"cm"))

g4= g4+ theme(axis.text.y.right = element_text(size=15, color = "black"),
              axis.text.x = element_text(size=14)) + ggtitle("  ST Soil")
g4=g4+  annotate(
  xmin = 4.425, xmax = 4.55,
  ymin = c(0.5,1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5,11.5,12.5,13.5,14.5),
  ymax = c(1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5,11.5,12.5,13.5,14.5,Inf),
  geom = "rect",
  fill = c("#3288C0",
           "#3288C0",
           "#D73E50",
           "#D73E50",
           "#FBDE89",
           "#3288C0",
           "#F6AC62",
           "#FBDE89",
           "#D73E50",
           "#FBDE89",
           "#D73E50",
           "#FBDE89",
           "#FBDE89",
           "#3288C0",
           "#FBDE89"))
#IPK
p5= read.csv2("Genus18S-IPK-aov0.05-vf.csv")
p5$Time= factor(p5$Time)

p5$Genus= factor(p5$Genus,
                 levels= c("Opisthonecta",
                           "Spumella",
                           "D3P05A02",
                           "Filamoeba",
                           "Lobochlamys",
                           "Chlamydomyxa",
                           "Colpoda"))
p5$Abundance_tax1 = p5$Abundance_tax*100

g6=ggballoonplot(p5,x="Time", y="Genus", fill= "Abundance",  size="Abundance_tax", color= "black") +
  labs(fill= "EF", size="Relative Abundance" )+ theme_bw()+
  scale_fill_viridis(option= "viridis",direction = 1, limits= c(0.015,0.35), na.value= "white")+
  guides(y.sec=guide_axis())+ theme(axis.text.y.left = element_blank())+
  theme(plot.margin=unit(c(0.1,7,0.1,1),"cm"))+
  guides(fill=guide_colorbar(order =1 ))+ scale_size_continuous(limits = c(0, 0.6), range = c(0, 16))+
  theme(axis.text.y.right = element_text(size=12),
        axis.text.x = element_text(size=10))
g6= g6+ theme(axis.text.y.right = element_text(size=15, color = "black"),
              axis.text.x = element_text(size=14))+ ggtitle("  LT Soil")

g6= g6 + annotate(
  xmin = 3.425, xmax = 3.55,
  ymin = c(0.5,1.5,2.5,3.5,4.5,5.5, 6.5),
  ymax = c(1.5,2.5,3.5,4.5,5.5,6.5,Inf),
  geom = "rect",
  fill = c("#68C0A5",
           "#5D529F",
           "#F6AC62",
           "#D73E50",
           "#5D529F",
           "#AAD2A1",
           "#68C0A5"))

## escala
eucariotas <- read_excel("C:/Users/esteb/Desktop/Investigacion/paper sip/re analisis Sip/graficas nuevas/Graficas Figura 3/colores-eucariotas.xlsx")

paleta14= c( "#D73E50", "#F6AC62", "#FBDE89",
             "#AAD2A1", "#68C0A5", "#3288C0", "#5D529F")

p2=ggplot(eucariotas, aes(Phylum, valor, fill= Phylum)) + geom_bar(stat= "identity") + scale_fill_manual(values=paleta14)+
  labs(fill= "Phylum") + theme(legend.text = element_text(size=13),
                               legend.title = element_text(size=14),
                               legend.key.size = unit(0.65, "cm"))
label3= ggpubr::get_legend(p2)

lab3=as_ggplot(label3)

G6=g4/g6 + plot_layout(heights = c(2.5,1))+ plot_annotation(tag_levels = "A") & theme(legend.position = "none")&
  theme(plot.tag = element_text(size = 16),
        title = element_text(size=16))

G7=G6 + inset_element(lab3, 1.85,6,0.95,1.05) + inset_element(lab2, 1.89,2.65,0.95,1.05)& ylab(NULL)

ggsave("Figure 4-Revised.pdf", G7, height = 10, width = 15.75)

```

